# class16-numpy1

Use the "Run" button to execute the code.

In [1]:
#Size of array can't be chnaged while in List size can be changed 
#Memory allocation is at different places in List while location of memory of location in Array is at one place
#Vector=>one dimensional array
#Array is fast

#### Arrays:
* 1.Faster
* 2.Contigous memory location
* 3.Same data types
* 4.If you want to increase size,recreate array


#### List:
* 1. Slow
* 2. Sparse memory (at different location of memory)
* 3. Different Data types
* 4. Can Dynamically grow


In [62]:
!pip install numpy

In [ ]:
#A comparision of numpy vs Lsit in python?


In [63]:
import numpy as np

In [5]:
p_list=range(1000000) #A list from 0-100000


In [6]:
p_list

range(0, 1000000)

In [7]:
numpy_array=np.arange(1000000) #An array from 0 t0 100000

In [8]:
#Multiply a list with 5


In [9]:
results=[]
for i in p_list:
    results.append(i*5)

In [10]:
#list Comprehension style  
%time for i in range(1000):results=[i*5 for i in p_list]

CPU times: user 1min 2s, sys: 1.78 s, total: 1min 4s
Wall time: 1min 4s


In [11]:
#Multiply numpy array wuth 5

In [12]:
%time numpy_array*5

CPU times: user 1.69 ms, sys: 23 µs, total: 1.72 ms
Wall time: 1.35 ms


array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

In [13]:
%time for i in range(1000):result=numpy_array*5

CPU times: user 626 ms, sys: 3.99 ms, total: 630 ms
Wall time: 629 ms


As we see above Time taken by Python list is quite more than time taken by numpy array 

### Numpy Array Creation Methods

In [14]:
one_d_array=np.zeros((10))
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
one_d_array=np.ones((10))
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
two_d_array=np.zeros((10,5))
two_d_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
x=np.zeros((3,2,5)) #depth=3,rows=2,columns=5

In [18]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
x.shape


(3, 2, 5)

In [20]:
#Array of custom elements

In [21]:
y=np.array([1,2,7,9,16,78,18,4]) #marzi ki array

In [22]:
y.shape


(8,)

In [23]:
z=y.reshape((2,4))
z

array([[ 1,  2,  7,  9],
       [16, 78, 18,  4]])

In [24]:
z.ndim

2

In [25]:
#Accessing Individual elements of array

In [26]:
z[0,3] # zeroth row, third 3rd column

9

In [27]:
#Slicing

In [28]:
z

array([[ 1,  2,  7,  9],
       [16, 78, 18,  4]])

In [29]:
z=z.reshape(4,2)
z

array([[ 1,  2],
       [ 7,  9],
       [16, 78],
       [18,  4]])

In [30]:
z[0:3] #slicing 

array([[ 1,  2],
       [ 7,  9],
       [16, 78]])

In [31]:
z[0:3,1]

array([ 2,  9, 78])

In [32]:
z[::2] # row indexing #The slice notation "z[::2]" means to start at the beginning of the array, 
                        #and select every 2nd element, and it will return the sub-array with those elements.

array([[ 1,  2],
       [16, 78]])

In [33]:
z[::,1]

array([ 2,  9, 78,  4])

In [34]:
y[[3,5]] #Fancy indexing

array([ 9, 78])

In [35]:
#Vectorized Operations

In [36]:
x=np.array([1,5,7])
y=np.array([3,2,6])

In [37]:
x+y

array([ 4,  7, 13])

In [38]:
x-y

array([-2,  3,  1])

In [39]:
x*y**2


array([  9,  20, 252])

### Shapes
`0000
 1111
 1111
 0000`

In [40]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
arr[0]=0
arr[4]=0


In [42]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [43]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
arr[1:-1,1:-1]=1

In [45]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# Questions:
#Create a Checkerboard Pattern:
#Football Ground:
##0000
##1111
##0000
##1111

#Cross Pattern:
##01110
##10101
##11011
##10101
##01110

 


In [47]:
np.empty((5,5)) # generating random or arbitary array 

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
#Comaprision between matrics
salary=np.array([25,6,7,89,43])

In [49]:
salary>66

array([False, False, False,  True, False])

In [50]:
salary[salary>55]

array([89])

In [51]:
np.sin(salary)

array([-0.13235175, -0.2794155 ,  0.6569866 ,  0.86006941, -0.83177474])

In [52]:
np.sqrt(salary)

array([5.        , 2.44948974, 2.64575131, 9.43398113, 6.55743852])

In [53]:
#Answers

In [54]:
# Creating Checker Pattern
a=np.ones((8,8))
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
a[::2,1::2]=0
a[1::2,::2]=0

In [56]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [57]:
# Generte Cross Pattern:
##01110
##10101
##11011
##10101
##01110

In [58]:
n=6
c=np.ones((n,n))


In [59]:
c[0,:1]=0
c[0,-1]=0
c[-1,-1]=0
c[-1,0]=0
c[1:-1,1:-1]=0
c[2:-2,2:-2]=0


In [60]:
c

array([[0., 1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1., 0.]])

In [83]:
n = 10
matrix = np.ones((n, n))
np.fill_diagonal(matrix, 0)
np.fill_diagonal(matrix[:, ::-1], 0)

In [84]:
matrix

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])